Updating ReadMe Documentation:
recloudstream/cloudstream pull request #1004
Opened 2024-03-21 20:27 UTC by KaiKitKobold

Since the initial Read.me documentation was lacking with helpful sources and information about the project, and sources relating to the project, I've updated the Read.Me, to include other links to the project and sections of content relating to various aspects of the project. 

Please let me know if this does not fit expectations; I can easily update it to improve it.

2024-03-21 20:40 UTC, KaiKitKobold commented
I Will Add that this is a first draft, and I expect this Commit to be flawed Initially anyway; I'll keep iterating until it gets a thumbs up from various Maintainers.

2024-03-21 22:28 UTC, KaiKitKobold commented
Read.Me has been updated. Please let me know of any potential errors and what needs to be changed or updated.

2024-03-21 23:04 UTC, Blatzar requested changes
Generally good, but needs a few fixes

2024-03-21 23:04 UTC, Blatzar commented on README.md
> +**Further details on creating extensions for CloudStream are found on our website. **
```suggestion
**Further details on creating extensions for CloudStream are found on our website.**
If you need help with development please come ask in our discord.
```

2024-03-21 23:04 UTC, Blatzar commented on README.md
> +Even if you can't contribute to the code or documentation, we always contribute to translation and language support. It's exceptionally appreciated; you can check our translation from the figure belo
```suggestion
Even if you can't contribute to the code or documentation it's always possible to [contribute](https://hosted.weblate.org/engage/cloudstream/) to the translations. It's exceptionally appreciated; you can check our translation status in the figure below. 
```

2024-03-22 00:08 UTC, KaiKitKobold commented
Hello @Blatzar! (I'm Sorry for accidentally deleting one of your suggestions; I didn't know what the Resolve conversation actually did until I pressed it.) 
I have updated my commit with the changes you specified above. Please let me know if anything else needs to be changed. I look forward to your feedback.

2024-03-22 00:43 UTC, KaiKitKobold commented
Oh Whoops, It seems that I missed a step, I apologize, I'll get started working on it right away.

2024-03-22 16:06 UTC, KaiKitKobold commented
Hello @Blatzar, I've updated the ReadME to include your and Green's suggestions; if you wish for anything in the issues header or anything else in the project to be fixed, please let me know.

2024-04-25 22:57 UTC, fire-light42 commented
Any update on this @Blatzar

2024-05-05 22:49 UTC, KaiKitKobold commented
@Blatzar, I am commenting to let you know that I'm still available and ready to update this project if needed.

2024-07-23 21:33 UTC, epireyn commented on README.md
> +While we **actively** accept issues and pull requests; We do require you fill out an [template](https://github.com/recloudstream/cloudstream/issues/new/choose) for issues, these include the following
I would change punctuation:
```suggestion
While we **actively** accept issues and pull requests, we do require you fill out an [template](https://github.com/recloudstream/cloudstream/issues/new/choose) for issues. These include the following:
```

2025-01-15 23:14 UTC, merged