SubDL subtitles provider
recloudstream/cloudstream pull request #1082
Opened 2024-05-09 10:41 UTC by KingLucius

- Adds SubDL subtitles provider.
- Imdb Id passing now correctly.

2024-05-09 13:15 UTC, KingLucius commented
there is another option that we can getMetaData() inside ShowMirrosDialog() and pass the imdb to openOnlineSubPicker()

2024-05-09 15:05 UTC, fire-light42 requested changes
Nice addition, however I will be a bit harsh with the code quality.

What you have done is hardcoded imdb into too many places using a string instead of a long, why?. This may work for this one thing, but does not allow for easy future expansion as it ties cs3 to imdb.

2024-05-09 15:05 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/syncproviders/providers/Subdl.kt
> +        AppUtils.tryParseJson<ApiResponse>(req.text)?.let {resp ->
`let resp = AppUtils.tryParseJson<ApiResponse>(req.text) ?: return results` or `return null`

2024-05-09 15:05 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/syncproviders/providers/Subdl.kt
> +            resp.subtitles?.forEach { subtitle ->
`results = resp.subtitles.map { }`

There is no reason to construct a mutableList when you can just collect it with map

2024-05-09 15:44 UTC, KingLucius commented on app/src/main/java/com/lagradost/cloudstream3/subtitles/AbstractSubtitleEntities.kt
> +        var imdb: String? = null,
Because originally it's ttNNNNN and most of the using of imdb will be as string with ttxxxxx, only opensubtitles uses it as it without tt

2024-05-09 15:47 UTC, KingLucius commented
> Nice addition, however I will be a bit harsh with the code quality.
> 
> What you have done is hardcoded imdb into too many places using a string instead of a long, why?. This may work for this one thing, but does not allow for easy future expansion as it ties cs3 to imdb.

In most cases you need and will use the imdb ID as a full one with ttxxxxx and that's the same format that be added from trakt & TMDB apis
Only Opensubtitles uses only the numbers without tt
So using it as string and only replace in Opensubtitles sub provider is the logic thing to do
To avoid adding the tt in most cases

2024-05-09 16:32 UTC, KingLucius commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/GeneratorPlayer.kt
> +        var imdbId: String? = null,
Can you elaborate? I don't get what you mean

2024-05-09 17:44 UTC, KingLucius commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/GeneratorPlayer.kt
> +        var imdbId: String? = null,
It can't be generic, it will loose its meaning as we need to provider all codes available at MainApi
Imdb, tmdb.. Etc

2024-05-09 17:46 UTC, fire-light42 commented
Alright, however normally with stuff like this (like mal and anilist) when it can be stored as an int is is stored as an int

2024-05-09 17:48 UTC, KingLucius commented
> Alright, however normally with stuff like this (like mal and anilist) when it can be stored as an int is is stored as an int

Sure, I think only imdb needs to be stored as string, all others would be stored as Int

2024-05-09 21:54 UTC, KingLucius commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/GeneratorPlayer.kt
> +        var imdbId: String? = null,
Totally agree, will check that 👍

2024-05-18 06:09 UTC, KingLucius commented
We can later update MainApi to store applicable IDs as int.
Then we can remove the toInt() later

2024-05-18 16:15 UTC, fire-light42 approved these changes

2024-05-18 16:15 UTC, merged