feat(TV UI): Accounts PIN login support
recloudstream/cloudstream pull request #1123
Opened 2024-06-08 07:29 UTC by KingLucius

- Default method on TV, If sync api supports authentication via PIN.
- You can local authenticating also.
- QR scanning for URL opening.

**Note**: CS logo can be added to QR code but the code was overkill as QR Lib recieve the logo as ByteArray so I removed it.

2024-06-08 12:45 UTC, IndusAryan commented
> * Default method on TV, If sync api supports authentication via PIN.
> 
>     * You can local authenticating also.
> 
>     * QR scanning for URL opening.
> 
> 
> **Note**: CS logo can be added to QR code but the code was overkill as QR Lib recieve the logo as ByteArray so I removed it.

can we embed an image overflow on the qr image itself in centre

2024-06-08 13:06 UTC, KingLucius commented
> > * Default method on TV, If sync api supports authentication via PIN.
> >   
> >   * You can local authenticating also.
> >   * QR scanning for URL opening.
> > 
> > **Note**: CS logo can be added to QR code but the code was overkill as QR Lib recieve the logo as ByteArray so I removed it.
> 
> can we embed an image overflow on the qr image itself in centre

it's already supported, only need the logo to be passed as byteArray, I have succesfully did it but then removed the code, I can do it again if you guys sees it's better

2024-06-08 19:18 UTC, fire-light42 requested changes
This is my initial review, more might come after I have tested it

2024-06-08 19:18 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsAccount.kt
> +                                                activity.getString(R.string.device_pin_error_message)
1. toast is thread safe
2. toast can take a stringres

2024-06-08 19:18 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsAccount.kt
> +                            api.authenticate(activity)
this is really weird to read, reverse this if statment so this is on top and else is the rest of the code

2024-06-08 19:18 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsAccount.kt
> +                                        delay(1000)
this entire setup is weird and prone to errors. Just use something like this https://developer.android.com/reference/android/os/CountDownTimer instead

2024-06-09 14:29 UTC, fire-light42 commented on app/src/main/res/values/strings.xml
> +    <string name="device_pin_error_message">"Can't get the device PIN code, try local authentication"</string>
Why prefix and suffix with " ????

2024-06-09 14:31 UTC, KingLucius commented on app/src/main/res/values/strings.xml
> +    <string name="device_pin_error_message">"Can't get the device PIN code, try local authentication"</string>
Mistake

2024-06-19 14:05 UTC, fire-light42 approved these changes
Works, and looks very nice 👍

2024-06-19 14:06 UTC, merged

2024-06-19 14:16 UTC, KingLucius commented
> Works, and looks very nice 👍 

Thanks, merged in the right time
I will add this to trakt sync api also 👍