Add sorting by release date
recloudstream/cloudstream pull request #1206
Opened 2024-07-22 13:19 UTC by epireyn

This adds library sorting by release date. Closes #103

2024-07-22 21:49 UTC, fire-light42 requested changes
Nice addition 👍

2024-07-22 21:49 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/syncproviders/providers/MALApi.kt
> +                    Instant.from(
I dont trust this to not throw an exception as `Throws: DateTimeException – if unable to convert to an Instant` 

Wrap this in a try catch

2024-07-24 20:07 UTC, fire-light42 requested changes

2024-07-24 20:07 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/ui/library/LibraryViewModel.kt
> +    ReleaseDateNew(R.string.sort_release_date_new),
This needs to be moved down after AlphabeticalA and AlphabeticalZ because the librarySortingMode is stored by its ordinal.

2024-07-28 22:43 UTC, fire-light42 approved these changes

2024-07-28 23:00 UTC, merged

2024-07-28 23:00 UTC, fire-light42 commented
🙏 Nice addition.

2024-07-29 08:25 UTC, aneesh1122 commented
Where is this? I can't find it

2024-07-29 13:14 UTC, aneesh1122 commented
> > Where is this? I can't find it
> 
> In prerelease 

I installed it but I can't find it anywhere. Could you please post a screenshot?

2024-07-29 16:21 UTC, aneesh1122 commented
> > > > Where is this? I can't find it
> > > 
> > > In prerelease 
> > 
> > I installed it but I can't find it anywhere. Could you please post a screenshot?
> 
> ![Screenshot_20240729-191036_CloudStream Beta_1.png](https://github.com/user-attachments/assets/777c1397-0aa6-483d-bb7d-9ccb224f5ce0)
> 
> 

I was looking for the sorting option in search results. It's actually in the library.

I wish it was also in search results.