Add system dark theme
recloudstream/cloudstream pull request #1208
Opened 2024-07-22 16:14 UTC by epireyn

This adds an option to set the theme according to the system's. Closes #341.

2024-07-22 21:40 UTC, fire-light42 requested changes

2024-07-22 21:40 UTC, fire-light42 commented on app/src/main/res/values-pl/array.xml
> +        <item>Material You (Android 12+)</item>
Why "(Android 12+)" that is simply redundant.

2024-07-23 06:10 UTC, epireyn commented
Indeed, I noticed afterwards but forgot to revert it.

On Mon, 22 Jul 2024, 23:41 firelight, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In app/src/main/res/values-pl/array.xml
> <https://github.com/recloudstream/cloudstream/pull/1208#discussion_r1687170575>
> :
>
> >          <item>Ciemny</item>
>          <item>Szary</item>
>          <item>Amoled</item>
>          <item>Flashbang</item>
> -        <item>Material You</item>
> +        <item>Material You (Android 12+)</item>
>
> Why "(Android 12+)" that is simply redundant.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/recloudstream/cloudstream/pull/1208#pullrequestreview-2192599253>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALP2YTFVIRURV5GV3NXE4ITZNV375AVCNFSM6AAAAABLIUOX56VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCOJSGU4TSMRVGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-23 17:50 UTC, C10udburst commented on app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsUI.kt
> +            val removeFunction = { text: String ->
maybe removeTheme would be more descriptive?

2024-07-24 19:32 UTC, fire-light42 requested changes
This makes system the default because of `settingsManager.getString(getString(R.string.primary_color_key), prefValues.first())`

"Dark" should be the default, so I need you to change it.

2024-07-25 00:32 UTC, Luna712 commented
> This makes system the default because of `settingsManager.getString(getString(R.string.primary_color_key), prefValues.first())`
> 
> "Dark" should be the default, so I need you to change it.

@fire-light42

If the intent is to always default to dark, wouldn't it make sense to instead force that to Dark as a default rather than `.first()` it seems that would be less prone to potential changes messing it up. Anyway it is up to you, that is just my personal opinion but there may also be a reason why not to do that. But doing it also just seems like it would better indicate the intended default as well.

2024-07-25 09:10 UTC, epireyn commented
> > This makes system the default because of `settingsManager.getString(getString(R.string.primary_color_key), prefValues.first())`
> > "Dark" should be the default, so I need you to change it.
> 
> @fire-light42
> 
> If the intent is to always default to dark, wouldn't it make sense to instead force that to Dark as a default rather than `.first()` it seems that would be less prone to potential changes messing it up. Anyway it is up to you, that is just my personal opinion but there may also be a reason why not to do that. But doing it also just seems like it would better indicate the intended default as well.

It would be the best, however it requires hard-coding the value. If it was to change, the themes wouldn't work at all. I reorder the list, it's no big issue.

2024-07-25 11:25 UTC, fire-light42 requested changes

2024-07-25 11:25 UTC, fire-light42 commented on app/src/main/res/values-tr/array.xml
> +        <item>System</item>
You forgot to reorder all arrays

2024-07-28 22:48 UTC, fire-light42 approved these changes

2024-07-28 23:01 UTC, merged

2024-07-28 23:02 UTC, fire-light42 commented
Now more people can be flashbanged by the white theme 🤩