Fix BackPressedCallback conflict between activities
recloudstream/cloudstream pull request #1258
Opened 2024-08-08 20:52 UTC by Luna712

There is another, more simple way to do this by just detatching the callback everytime it is pressed in DownloadedPlayerActivity, however, I figured this method was more future-proofed if more activities are added later so went with this, but if you want me to go to do the more simple method I can also.

2024-08-08 22:38 UTC, fire-light42 commented
Will be merged after testing. 👍

2024-08-15 22:02 UTC, fire-light42 requested changes
This breaks the current attachBackPressedCallback implementation by removing old callbacks. You can test this by pressing back on the mainpage on tv, then you will get a "do you want to exit dialog", however if you go into downloads then back this dialog wont appear.

2024-08-16 00:29 UTC, Luna712 commented
> This breaks the current attachBackPressedCallback implementation by removing old callbacks. You can test this by pressing back on the mainpage on tv, then you will get a "do you want to exit dialog", however if you go into downloads then back this dialog wont appear.

@fire-light42 

This happens on current pre release also, I can fix it in this PR but it is unrelated to the purpose of this PR, which in my opinion fixes a much more annoying and consistent issue where back presses can stop working completely and you have force stop the app to fix. So I think it would make more sense to fix that in a follow-up. But it's up to you.

2024-08-16 17:22 UTC, fire-light42 approved these changes

2024-08-16 17:22 UTC, merged