feat(DRM): License URL support for Extensions
recloudstream/cloudstream pull request #1432
Opened 2024-12-21 08:45 UTC by KingLucius

Extensions developers can use OnlineDrmExtractorLink to provide the Drm license URL.

2024-12-29 03:37 UTC, fire-light42 requested changes
Why do you need an extra type, just extend DrmExtractorLink instead.

2024-12-29 03:39 UTC, fire-light42 commented
This will also be blocked until stable like #1216

2024-12-29 04:47 UTC, KingLucius commented
> Why do you need an extra type, just extend DrmExtractorLink instead. 

We can go the other approach extending DrmExtractorLink and based on the existence of keyUrl will setup Media3 configuration online/offline

2025-01-18 00:52 UTC, fire-light42 commented on library/src/commonMain/kotlin/com/lagradost/cloudstream3/utils/ExtractorApi.kt
> +        licenseUrl: String? = null,
This will break the API, so this will be blocked until stable.

2025-01-18 05:20 UTC, KingLucius commented on library/src/commonMain/kotlin/com/lagradost/cloudstream3/utils/ExtractorApi.kt
> +        licenseUrl: String? = null,
I saw that if we are going to wait stable anyway, I can add the parameter like this

2025-02-04 23:31 UTC, LagradOst approved these changes

2025-02-04 23:31 UTC, merged