Add volume booster above 100%
recloudstream/cloudstream pull request #1444
Opened 2024-12-29 22:32 UTC by Luna712

Not completely done still need to do some more work on UI and make the volume button effect this.

Resolves #1086

2024-12-30 22:58 UTC, Luna712 commented
This *should* be ready for review now...

2025-01-04 21:13 UTC, fire-light42 requested changes
I have only tested this briefly so more bugs might be found later. However at the moment you have two critical bugs that I require you to fix.
1. The showtoast is spammed when dragging over from under 100% to 100%. This might not seem like an issue to you depending on your OS, but for me it flickers. 
2. The color of the left bar even when under 100% is slightly more yellow/orange then the right brightness bar.

2025-01-04 23:30 UTC, Luna712 commented
> I have only tested this briefly so more bugs might be found later. However at the moment you have two critical bugs that I require you to fix.
> 
> 1. The showtoast is spammed when dragging over from under 100% to 100%. This might not seem like an issue to you depending on your OS, but for me it flickers.
> 2. The color of the left bar even when under 100% is slightly more yellow/orange then the right brightness bar.

@fire-light42 

Both those *should* be fixed although I couldn't really reproduce the first one.

2025-01-05 01:44 UTC, fire-light42 commented
Issue two is fixed, but issue one remain. I recommend to look at the log in android studio as showToast should print out repeatedly.

2025-01-05 01:46 UTC, fire-light42 commented
While issue two is fixed, I would much rather you make the background progress of the orange bar invisible so it does not change the white background color at all above 100%.

2025-01-05 02:37 UTC, Luna712 commented
> While issue two is fixed, I would much rather you make the background progress of the orange bar invisible so it does not change the white background color at all above 100%.

I tried numerous ways to do this and nothing seemed to work. Only thing that did work was a new drawable but I don't want to do that here,

2025-01-05 03:04 UTC, Luna712 commented
> Issue two is fixed, but issue one remain. I recommend to look at the log in android studio as showToast should print out repeatedly.

I decided to just have toasts show once as they get annoying anyway if you change volume a lot, and I think you can get the point after the first time anyway.

2025-01-17 23:55 UTC, fire-light42 requested changes

2025-01-17 23:55 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +            val level1Color = Color.WHITE
This entire part can be removed by adding `android:progressTint="@color/colorPrimaryOrange"`

2025-01-17 23:55 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +                                if (isLayout(PHONE or EMULATOR)) {
Why not tv, can you please explain why only the tv layout does not get volume boosting?

2025-01-17 23:55 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +                            if (currentRequestedVolume == 0.0f) {
This can cause a very bad experience for the user, and is why it always queried in the old code. To exemplify this, imagine that the user watch a movie on the max volume, pauses the app, and switched to another app. Under the course of a few hours lowers the volume, then comes back. 

In this case the volume would still be low, however the moment any volume is changed by only an single step the movie is back at maximum volume.

2025-01-17 23:55 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +            if (isAdjustingVolume && currentRequestedVolume <= 1.0f && nextVolume >= 1.0f) {
`isAdjustingVolume` just feels like a bad solution for this.

2025-01-17 23:55 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +                showToast(R.string.volume_exceeded_100)
This does not show up if we start a video at exactly 100% volume.

2025-01-18 00:00 UTC, Luna712 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +                                if (isLayout(PHONE or EMULATOR)) {
Because TVs don't need it as much and a lot might not support it. In essence it doesn't do anything and instead would cause the volume bar used on phones to appear on TV when overriding the volume key yet sometimes it doesn't do anything different. So decided to just disable it here.

2025-01-18 00:01 UTC, Luna712 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +            if (isAdjustingVolume && currentRequestedVolume <= 1.0f && nextVolume >= 1.0f) {
If it is I will probably just abandon this as I spent probably 4-5 hours trying to find some better solution lol. I don't have it in me to find another solution again unless you have some suggestion?

2025-01-18 00:03 UTC, Luna712 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +            val level1Color = Color.WHITE
Whoops lol. That was a leftover from an old way this was done.

2025-01-18 00:05 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +                                if (isLayout(PHONE or EMULATOR)) {
If so, please note this with a comment.

2025-01-18 00:07 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +                                if (isLayout(PHONE or EMULATOR)) {
Also, if some devices do not support this, is there a possibility to query this support? Then disable in the case of no support.

2025-01-18 00:08 UTC, Luna712 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +                                if (isLayout(PHONE or EMULATOR)) {
There probably is I just didn't think it was all that useful on TVs so just disabled it on the layout. I will add a comment though.

2025-01-18 00:12 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +            if (isAdjustingVolume && currentRequestedVolume <= 1.0f && nextVolume >= 1.0f) {
Well if you only want to have this lock feature, then just add a variable called `isVolumeLocked = currentVolumePercentage < 100.0f` or similar at the start of any swipe. 

Additionally with this you could reset hasShownVolumeToast by `if (isVolumeLocked) { hasShownVolumeToast = false; }` in the very next line to allow for more then 1 toast per player instance.

2025-01-18 00:13 UTC, Luna712 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +            if (isAdjustingVolume && currentRequestedVolume <= 1.0f && nextVolume >= 1.0f) {
That's a great idea actually.

2025-02-05 00:20 UTC, Luna712 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +                showToast(R.string.volume_exceeded_100)
I *think* this should be fixed...

2025-02-05 00:20 UTC, Luna712 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +            if (isAdjustingVolume && currentRequestedVolume <= 1.0f && nextVolume >= 1.0f) {
Now done.

2025-02-05 00:21 UTC, Luna712 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +                            if (currentRequestedVolume == 0.0f) {
I *think* I fixed this issue.

2025-02-05 00:21 UTC, Luna712 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +                                if (isLayout(PHONE or EMULATOR)) {
I added a comment for this now.

2025-02-05 00:21 UTC, Luna712 commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +            val level1Color = Color.WHITE
Fixed

2025-02-11 14:13 UTC, fire-light42 requested changes
This unfortunately still have some bugs, namely that swiping is inconsistent with pressing the volume button. For example, you cant go above 100% with the vol button, and will simply be greeted with the "slide up again" toast repeatedly, but this does not happen when sliding. 

Additionally, if we go outside the application, lower the volume then come back, sliding does not affect the volume the same as pressing the vol button. I would personally reset the boost if the volume in onResume does not match up with the last requested volume in onPause.

2025-02-28 23:05 UTC, fire-light42 commented
@Luna712 Do you need help finishing the PR?

2025-03-09 03:41 UTC, Luna712 commented
> @Luna712 Do you need help finishing the PR?

@fire-light42 

So sorry I got very busy IRL if someone wants to take this over and finish it I'm absolutely okay with that otherwise I will finish it if/when I have time *eventually*

2025-04-17 17:08 UTC, fire-light42 approved these changes

2025-04-17 17:13 UTC, merged