Fix scroll for Library TV layout
recloudstream/cloudstream pull request #695
Opened 2023-10-16 10:12 UTC by KingLucius

2023-10-20 12:13 UTC, fire-light42 requested changes
NestedScrollView = very bad as it has to render every single item that exist as it cant recycle. Explain really well why this is nessessary and why you can fix it in any other way or else this will never be merged

2023-10-20 16:51 UTC, KingLucius commented
The layouts description says if you have multi scrolls in same layout then usr nestedscrollview, i am open to any other suggestion no issue

2023-10-31 09:46 UTC, KingLucius commented
Updated the fix without NestedScrollView

2023-11-02 20:02 UTC, fire-light42 approved these changes

2023-11-02 20:03 UTC, merged