Add support for profile locks
recloudstream/cloudstream pull request #733
Opened 2023-10-28 21:16 UTC by Luna712

Resolves #604

2023-10-28 22:26 UTC, fire-light42 commented
While the UI and code is very good it has a major flaw that needs fixing before it gets merged. It can be bypassed all together by holding down the locked profile (to edit it) then pressing apply. Apply should only change the account to that account if the pin was also entered

2023-10-28 22:27 UTC, fire-light42 requested changes
Very good code

2023-10-28 23:03 UTC, Luna712 commented
> While the UI and code is very good it has a major flaw that needs fixing before it gets merged. It can be bypassed all together by holding down the locked profile (to edit it) then pressing apply. Apply should only change the account to that account if the pin was also entered

@fire-light42 

Sorry If I messed up the code in newer one, a bit messier code, but much UX improvement, automatically logs in when the pin is correct and displays good error message (dynamically) when changing the pin, but it made a bit messier, which I apologize for if it is a problem I can fix.

2023-10-28 23:06 UTC, Luna712 commented
The bypass issue is a good catch and I am working on it.

2023-10-28 23:11 UTC, Luna712 commented
My new version of this is somewhat inspired by how it works on Netflix, but in my opinion better UI.

2023-10-28 23:12 UTC, fire-light42 commented
The change still suffers from the same bug along with another one that might have been present in the last one. But if you press lock then dismiss it, it will still have the checked as locked but not be locked

2023-10-28 23:12 UTC, fire-light42 commented
Change UI all you like, however this will not get merged before all bugs are fixed

2023-10-28 23:30 UTC, Luna712 commented
@fire-light42 I *think* I fixed those bugs

2023-10-29 00:15 UTC, fire-light42 commented
Still not fixed the dismiss issue. 
1. Press add a new profile
2. Press lock
3. Dismiss the lock by pressing outside the dialog
4. It will still show locked, but will be be locked

2023-10-29 00:17 UTC, fire-light42 commented
Also, a lock on default should not be possible as that can also be bypassed by creating an account and then deleting it

2023-10-29 00:20 UTC, Luna712 commented
> Still not fixed the dismiss issue.
> 
> 1. Press add a new profile
> 2. Press lock
> 3. Dismiss the lock by pressing outside the dialog
> 4. It will still show locked, but will be be locked

I can not reproduce this, clicking outside the dialog dismissing it still keeps ir locked for me.

2023-10-29 00:24 UTC, fire-light42 commented
![image](https://github.com/recloudstream/cloudstream/assets/147925818/d3928012-1ec8-4c62-b4a5-267c7ce16ef9)
![image](https://github.com/recloudstream/cloudstream/assets/147925818/4b37ae60-252a-4e6c-9f06-1a259236652e)
![image](https://github.com/recloudstream/cloudstream/assets/147925818/6ef8ca73-9a0f-49cb-96d2-44d36a908a4c)
![image](https://github.com/recloudstream/cloudstream/assets/147925818/a8d3976b-d4fe-424b-8efe-fe753d84c4a1)

2023-10-29 00:25 UTC, Luna712 commented
@fire-light42 this does not appear to happen to me still, tried many combinations and it didn't happen.

2023-10-29 00:26 UTC, Luna712 commented
oh wait I see

2023-10-29 00:27 UTC, Luna712 commented
I thought you were talking about if locked to unset lock you could bypass needing the current lock

2023-10-29 00:29 UTC, Luna712 commented
I'll finish this in about two hours

2023-10-29 00:29 UTC, fire-light42 commented
Also, from a ux perspective autoclosing if correct with 4 chars is very bad as if I click more than how many items there are it will close it when I try to edit the profile. Then is the bug that I cant remove a pin from a profile

2023-10-29 00:33 UTC, Luna712 commented
> Also, from a ux perspective autoclosing if correct with 4 chars is very bad as if I click more than how many items there are it will close it when I try to edit the profile. Then is the bug that I cant remove a pin from a profile

It only closes automatically if you enter the correct pin

2023-10-29 00:34 UTC, Luna712 commented
I'm not sure under what circumstances you couldn't remove a pin, it doesn't auto close when creating a new pin either.

2023-10-29 01:02 UTC, Luna712 commented
Also it is forcibly limited to 4 characters in layout with `android:maxLength="4"` so there could never be more.

2023-10-29 02:33 UTC, Luna712 commented
@fire-light42 the bug should be fixed as well as no pins on default account

2023-10-29 14:02 UTC, fire-light42 commented
I am still unable to remove a pin from an account.

and while your hiding of lock on default account is fine, it becomes impossible to actually edit the default account if it is already locked. This might be an illegal state right now, but I would still like this fixed if we have to change this in the future

2023-10-29 14:05 UTC, fire-light42 commented
Same with the auto unlocking when entering the correct password. I much rather have a button as stated before it is easy to click one time too many on a phone

2023-10-29 14:10 UTC, fire-light42 commented
![image](https://github.com/recloudstream/cloudstream/assets/147925818/99234075-1722-45c8-9103-e3e262e2749f)
![image](https://github.com/recloudstream/cloudstream/assets/147925818/84956f5e-a77d-4d83-a45b-257cb746f3d9)
![image](https://github.com/recloudstream/cloudstream/assets/147925818/260ba885-2cb6-4787-ac2e-5ffae7f56910)
![image](https://github.com/recloudstream/cloudstream/assets/147925818/fff175d6-047a-4294-bbdd-d4962fb74ec6)
![image](https://github.com/recloudstream/cloudstream/assets/147925818/b8da2192-d27b-48c9-8ae9-33d1ff4b75cd)
As you can see, I am unable to remove a lock from an account

2023-10-29 14:14 UTC, fire-light42 commented
https://github.com/recloudstream/cloudstream/assets/147925818/d7e08a2c-5b94-4485-b411-2012b310725b

And this is the UX issue I am talking about. you click too much and then you get kicked out without changing anything

2023-10-29 14:16 UTC, fire-light42 commented
Auto doing something is very bad UX wise as it does something you dont want in case of slightly bad input

2023-10-29 16:34 UTC, Luna712 commented
> Auto doing something is very bad UX wise as it does something you dont want in case of slightly bad input. This can be fine for TV input as keys are real button presses, but on a screen it is easy to double tap or missclick

Take Netflix for example which does this exact behavior, they have whole teams that decide on the best UX, so I did something similar as I felt it would be good behavior if something like they do it, even on mobile. I can make it only do so on TV, but I still don't personally feel it should. It makes it easier to only have to type a PIN and not have to press other keys or something to finalize logging in. It is only 4 characters, if you double tap or misclick you just do it again, it doesn't close if the PIN is wrong, it just clears and you can type again, it is a password field so you can't see the whole thing anyway, and going back to try one digit different can be just as bad and it's easier to type 4 characters again.

2023-10-29 16:43 UTC, fire-light42 commented
> > Auto doing something is very bad UX wise as it does something you dont want in case of slightly bad input. This can be fine for TV input as keys are real button presses, but on a screen it is easy to double tap or missclick
> 
> Take Netflix for example which does this exact behavior, they have whole teams that decide on the best UX, so I did something similar as I felt it would be good behavior if something like they do it, even on mobile. I can make it only do so on TV, but I still don't personally feel it should. It makes it easier to only have to type a PIN and not have to press other keys or something to finalize logging in. It is only 4 characters, if you double tap or misclick you just do it again, it doesn't close if the PIN is wrong, it just clears and you can type again, it is a password field so you can't see the whole thing anyway, and going back to try one digit different can be just as bad and it's easier to type 4 characters again.

As I said, it is fine on tv, but NOT on phone, and this is when we edit the account, not when we login. And no, this happend to me several times by accident when testing it so it is VERY bad UX. If you want to solve this without a button then make the account dialog not dismiss when clicking outside

2023-10-29 16:54 UTC, Blatzar commented
The issue here is that the keyboard gets lowered when done which moves the UI unexpectedly, in addition to the fact that the dialog is dismissable. 

Auto open is nice, that's how android does it, but it comes with both an indication of how many characters are entered and a sizable animation to react that the phone is opened.

Either go all in and add a unlock animation of ~250ms to prevent accidental touches or make the other dialog non cancelable (setCancelable(false)), at least for ~250ms after unlock. I think that is agreeable.

2023-10-29 17:28 UTC, Luna712 commented
Fixed some issues but one issue still remains when setting pin, clicking the done button. I'll fix it soon.

2023-10-29 19:16 UTC, Blatzar commented
Nice! setCanceledOnTouchOutside is even better than setCancelable :pray:

2023-10-29 19:52 UTC, Luna712 commented
Ok, I *think* everything is fixed now. Thanks again to both @Blatzar and @fire-light42 for the review and suggestions on this as well. I *hope* that's all, if not let me know and I'll change again.

2023-10-29 22:21 UTC, Luna712 commented
@fire-light42 @Blatzar 

![Screenshot_20231029_161844_CloudStream Debug](https://github.com/recloudstream/cloudstream/assets/142361265/4a1cdc44-f6c9-494d-b581-8a7314ccedc2)

I've also been working on a new account select page that allows pin protection at startup also, still more work, like auto focusing on last account, etc... and I'm not even sure if it's really something you want, but it is an option if so, it was mostly just a PoC for me to see how it would really work, and potential UX/UI behind it.

2023-10-29 22:24 UTC, Luna712 commented
It seems to load a lot faster that way also, well loads account selection faster than normal without, then loads main page faster after selecting account.

It might just be my connection though.

2023-10-29 22:24 UTC, Blatzar commented
Wonderful! That is a very requested feature :pray: 
I think a lot of TV users would be eternally grateful for this feature

2023-10-29 22:25 UTC, Blatzar commented
And your PoC already looks very good :drooling_face:

2023-10-29 22:39 UTC, Luna712 commented
> Wonderful! That is a very requested feature 🙏 I think a lot of TV users would be eternally grateful for this

@Blatzar 

Glad to hear its something that could be used then! I opened my draft PR in #736

2023-10-30 00:07 UTC, fire-light42 commented
Will have a look at both tomorrow and hopefully merge both. it looks :fire:

2023-10-30 04:27 UTC, Luna712 commented
> Will have a look at both tomorrow and hopefully merge both. it looks 🔥

@fire-light42 

Thanks a ton! Though, if you're going to merge both, forget this one, and just merge the other one please, it includes this patch, if it will take longer to get that one merged, this can be merged first and I'll rebase the other, its just more work.

2023-10-30 04:38 UTC, Luna712 commented
Marking as draft, you can unmark and merge this if you want to do this first, but a major reason I did the account selection PR was to support profile locks from startup so to ensure that had to do it there also, so this isn't needed if the other one is merged. Only if it will take longer/needs a lot more work.

2023-10-30 22:27 UTC, closed without merging