refactor: general and ui settings and added explicit unstable api opt ins
recloudstream/cloudstream pull request #787
Opened 2023-11-28 11:33 UTC by IndusAryan

2023-12-07 20:28 UTC, fire-light42 requested changes

2023-12-07 20:28 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsGeneral.kt
> +    return conf?.locales?.toString() ?: "en"
Big no, we dont want this app only accessible for API 24. Afaik this will crash for everyone that goes into settings rn on low sdk ver

2023-12-08 16:31 UTC, fire-light42 requested changes

2023-12-09 14:09 UTC, fire-light42 approved these changes

2023-12-09 14:10 UTC, IndusAryan commented on app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsGeneral.kt
> +        conf?.locales?.toString() ?: "en"
yes

2023-12-13 21:18 UTC, merged