extractor: added vidplay and fix few extractors
recloudstream/cloudstream pull request #795
Opened 2023-12-04 07:37 UTC by Sofie99

2023-12-05 08:57 UTC, b4byhuey commented
Can you fix Dailymotion? or can you conver from aniyomi [here](https://github.com/aniyomiorg/aniyomi-extensions/raw/master/lib/dailymotion-extractor/src/main/java/eu/kanade/tachiyomi/lib/dailymotionextractor/DailymotionExtractor.kt)

2023-12-07 20:25 UTC, fire-light42 requested changes
We dont want to ddos github for every call to geturl, save it to a local variable even if app.get may be cached it does not hurt to explicitly cache it

2023-12-07 20:25 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/extractors/Vidplay.kt
> +        return app.get("https://raw.githubusercontent.com/Claudemirovsky/worstsource-keys/keys/keys.json")
this should be cached in a local variable

2023-12-08 00:05 UTC, fire-light42 approved these changes

2023-12-08 00:05 UTC, fire-light42 commented
Understandable, I can merge this now if you want

2023-12-08 16:28 UTC, merged