add prevent option in CloudflareKiller
recloudstream/cloudstream pull request #808
Opened 2023-12-10 17:14 UTC by Sofie99

2023-12-12 13:57 UTC, b4byhuey commented
Please look [here](https://github.com/aniyomiorg/aniyomi-extensions/blob/master/lib/chillx-extractor/src/main/java/eu/kanade/tachiyomi/lib/chillxextractor/ChillxExtractor.kt), aniyomi get Chilx key from the body

2023-12-13 19:46 UTC, fire-light42 requested changes

2023-12-13 19:46 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/network/CloudflareKiller.kt
> +        val response = chain.proceed(request)
Suppose cookies are not null then this line always tries to do a request without cookies and only after that it shoots another request with cookies at line 67. This wastes a request.

2023-12-13 20:34 UTC, fire-light42 approved these changes

2023-12-15 14:34 UTC, merged

2023-12-16 12:56 UTC, fire-light42 commented
![Screenshot_20231216_182028_CloudStream_Beta](https://github.com/recloudstream/cloudstream/assets/147925818/ed46d80a-a932-4bac-9013-7d7dc95273de)
This might need to be reverted