feat(ui): tap video duration to toggle remaining time counter
recloudstream/cloudstream pull request #878
Opened 2024-01-13 11:40 UTC by IndusAryan

2024-01-16 17:38 UTC, fire-light42 commented
Why is this draft? do you want a review?

2024-01-16 18:25 UTC, IndusAryan commented
@fire-light42 i thought you will ask some minor changes, anyway it can be merged, undrafting it now

2024-01-19 19:56 UTC, fire-light42 commented
The code looked fine, **HOWEVER** when testing it I found that it was unsynced af making it feel shitty and it does not save the setting between runs. 

The first issue can be solved by binding the update to the text change of the position set by exo, this also removes the need to a looper
```kotlin
exoPosition.doOnTextChanged { _, _, _, _ ->
    updateRemainingTime()
}
``` 
and dont forget
```kotlin
val remainingTimeSeconds = (duration - position + 500) / 1000 // this is due to rounding
```
The second issue can be solved with a PreferenceDelegate
eg `var resizeMode : Int by UserPreferenceDelegate("resize_mode", 0)` with a bool instead

2024-01-19 19:56 UTC, fire-light42 requested changes
See above

2024-01-20 08:30 UTC, IndusAryan commented
> See above

so i made and tested these desired changes ,  now it is going with sync properly and i also replaces the comment // cs is ott itself to cs3 is media center itself so that it dont provoke  any  unwanted heat or issue and Thanks for telling about preference delegates, i had no idea about them or their existence .

can you tell me about this method what does _ _ _ do, do they ignore parameters that are not present
```  playerBinding?.exoPosition?.doOnTextChanged { _, _, _, _ ->
            updateRemainingTime()
        } ```
        
        because i experimented first with
        ```  playerBinding?.exoPosition?.doOnTextChanged (
            updateRemainingTime())
             ```
             but it crashed and turned update function to 
             ```char sequence , int , int  -> unit ......
             return updatingtime // this was flagged as recursive call by ide```
             
             finally there is one thing is that we call stopupdating remainingtime onDestroy , and that turn preference to 0 , so the setting only applies to a session, for example if user goes to next episode his seting work, but in different video file he has to press duration again , this can be repaired by not calling the stop on destroy but idk what repurcussion it can have in both tv or mobile.

2024-01-20 08:34 UTC, IndusAryan commented
because i experimented first with,
        
        ```kotlin
        playerBinding?.exoPosition?.doOnTextChanged (
            updateRemainingTime())```
            
             but it crashed and turned update function to 
             ```char sequence , int , int  -> unit ......
             return updatingtime // this was flagged as recursive call by ide```
             
             finally there is one thing is that we call stopupdating remainingtime onDestroy , and that turn preference to 0 , so the setting only applies to a session, for example if user goes to next episode his seting work, but in different video file he has to press duration again , this can be repaired by not calling the stop on destroy but idk what repurcussion it can have in both tv or mobile.

2024-01-20 15:39 UTC, fire-light42 requested changes

2024-01-21 18:22 UTC, IndusAryan commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +        playerBinding?.exoPosition?.doOnTextChanged { _, _, _, _ ->
i think i got it thsi time

2024-01-21 18:22 UTC, IndusAryan commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +    private fun startUpdatingRemainingTime() {
created

2024-01-21 18:22 UTC, IndusAryan commented on app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt
> +    private var durationMode : Int by UserPreferenceDelegate("duration_mode", 0)
yes

2024-01-21 19:10 UTC, fire-light42 approved these changes

2024-01-21 19:11 UTC, merged