feat(ui): ask users to set ignore battery optimisation for proper downloads and notifications
recloudstream/cloudstream pull request #915
Opened 2024-01-22 15:12 UTC by IndusAryan

diwali gift

2024-01-23 15:39 UTC, fire-light42 requested changes
This is very good download wise, but VERY bad UX wise. You want as few fullscreen popups as possible. 

1. You use REQUEST_IGNORE_BATTERY_OPTIMIZATIONS wrong
2. No option for retrying
3. No option for ignore
4. UserPreferenceDelegate is only local and cant actually keep track if the app is optimized or not, get the current status before requesting or rerequesting 
5. Only request this ***when*** downloading as it is unnecessary otherwise. 
6. Why only after M?

2024-01-23 15:39 UTC, fire-light42 commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
You request REQUEST_IGNORE_BATTERY_OPTIMIZATIONS without using  ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS

2024-01-23 15:39 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/MainActivity.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && !isAppOptimised && !isTrueTvSettings()
Another annoying popup when installing the app, this is not what we want. This should only show up when actually trying to download stuff.

2024-01-23 15:39 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/MainActivity.kt
> +    private fun showBatteryOptimizationDialog() {
This dialog also pop up every time until you press ok, making it VERY anoying

2024-01-23 15:39 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/MainActivity.kt
> +            showBatteryOptimizationDialog()
This also has no settings related option to access this after doing it for the first time

2024-01-23 15:39 UTC, fire-light42 commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
Look at https://stackoverflow.com/questions/44862176/request-ignore-battery-optimizations-how-to-do-it-right

2024-01-23 15:39 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/MainActivity.kt
> +        private var isAppOptimised : Boolean by UserPreferenceDelegate("isAppOptimised", false)
UserPreferenceDelegate is just a wrapper for set/get key, so restoring a backup skips this even if it is not optmized

2024-01-26 18:53 UTC, IndusAryan commented
>     4. UserPreferenceDelegate is only local and cant actually keep track if the app is optimized or not, get the current status before requesting or rerequesting

 i used power manager to get status of optimization before prompting, the problem i faced that after setting unrestricted , it takes hours for the status to get updated, that too different, maybe instantly in some devices turning feature into a jackass bug.

>     6. Why only after M?

in below marshmallow, battery savers dont doze apps that are in foreground, the fu*kery started in marshmallow api 6

2024-02-15 23:26 UTC, KingLucius commented
Check this if you want some ideas
https://github.com/WaseemSabir/BatteryPermissionHelper

2024-02-16 13:22 UTC, IndusAryan commented
> Check this if you want some ideas https://github.com/WaseemSabir/BatteryPermissionHelper

this lib look like a beta and tested for less sample size of vendors

2024-02-16 13:27 UTC, KingLucius commented
I think if we should do this, i suggest it as a step of the intial setup.

2024-02-16 13:32 UTC, IndusAryan commented
that's already denied by firelight in 5th point of review, the setup itself looks very annoying

2024-03-03 01:07 UTC, fire-light42 commented
> we have 2 things now, should there be a preference also to set this, if yes then in which settings?
> 
> should the cancel button permanently dismiss the dialog forever?
> 
> @fire-light42 @KingLucius

Sorry for the late reply, but if you want to get this merged it should also be added in settings and if you dismiss it then dont ask again (ever). Then you should also remove requireContext() as that WILL crash android. Also isTruePhone = !isTvSettings() that is why we dont have that function.

2024-03-06 12:32 UTC, IndusAryan commented
@fire-light42 i have pushed some final changes and tested on my side good, there is preference as well as it dismisses forever when canceled, but i couldnt understand why requireContext() needs to be removed, because app crashes and sometimes things dont work without it, lacking context in logcat, it preference also it works good and opens info directly.

2024-03-06 16:29 UTC, fire-light42 commented
> but i couldnt understand why requireContext() needs to be removed

Because sometimes android just decides that there is no context for whatever reason, and that causes the app to crash. So you always want to treat context as a nullable variable that cant be trusted. Both the android docs and examples use requireContext, but in cs3 we want to avoid that as much as possible, as we KNOW that it causes a significant amount of crashes because android just sucks.

2024-03-07 11:20 UTC, IndusAryan commented
> Because sometimes android just decides that there is no context for whatever reason, and that causes the app to crash. So you always want to treat context as a nullable variable that cant be trusted. Both the android docs and examples use requireContext, but in cs3 we want to avoid that as much as possible, as we KNOW that it causes a significant amount of crashes because android just sucks.

i have first tried defining ctx as nullable context, if not available it tries obtaining one as mentioned that android causes it, the dialog invocation is under the run catching that will pevent app crash if both ctx are absent, it this approach OK?

2024-03-22 21:54 UTC, fire-light42 reviewed
Minor changes before merge

2024-03-22 21:54 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsGeneral.kt
> +            getPref(R.string.battery_optimisation_key)?.isEnabled = false
getPref(R.string.battery_optimisation_key)?.isEnabled = isLayout(PHONE)

2024-03-22 21:54 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/utils/PowerManagerAPI.kt
> +        val isOptimizedShown = PreferenceManager.getDefaultSharedPreferences(context)
isOptimized***Not***Shown

2024-03-22 21:54 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/utils/PowerManagerAPI.kt
> +        } catch (e: Exception) {
t : Throwable as Exception does not protect you from errors

2024-03-22 21:54 UTC, fire-light42 commented on app/src/main/java/com/lagradost/cloudstream3/utils/PowerManagerAPI.kt
> +                    .setPositiveButton(R.string.ok) { _, _ ->
not open?

2024-03-25 00:18 UTC, fire-light42 approved these changes

2024-03-25 00:18 UTC, merged