fix(hotfix): bottom sheet appearing when turning biometrics off and remove toast.
recloudstream/cloudstream pull request #971
Opened 2024-03-08 09:04 UTC by IndusAryan

this needs some talk in the issue before being undrafted

closes #969

2024-03-08 17:38 UTC, Luna712 requested changes

2024-03-08 17:38 UTC, Luna712 commented on app/src/main/java/com/lagradost/cloudstream3/MainActivity.kt
> -                showToast(R.string.phone_not_secured, LENGTH_LONG)
phone_not_secured message is now unused and can be removed from values also.

2024-03-08 22:59 UTC, Luna712 approved these changes

2024-03-09 20:41 UTC, Luna712 commented
@IndusAryan I wonder if maybe you should have to confirm biometrics before it can even be enabled also? iE enter biometrics once when enabling and if it fails don't actually enable also.

2024-03-10 05:28 UTC, IndusAryan commented
this was thought as well as tried, to get this it requires bringing interface onAuthenticationSuccess in the accountSetting, but it requiresActivity() to work and context, but now i have learned context more , will try again.

2024-03-10 05:50 UTC, Luna712 commented
> this was thought as well as tried, to get this it requires bringing interface onAuthenticationSuccess in the accountSetting, but it requiresActivity() to work and context, but now i have learned context more , will try again.

@IndusAryan 

This is probably something I could help with if you need/want?

2024-03-10 07:42 UTC, IndusAryan commented
i will draft this and push changes you can review them, or co commit them.

2024-03-10 17:09 UTC, Luna712 commented
@IndusAryan can we unmark this as draft and do the rest in a separate PR, this is quite important to get merged for me, especially that random toast is pretty annoying as it even appears on TV which doesn't even support biometrics?

2024-03-10 22:15 UTC, merged